### ISSUE TITLE
Server closes everytime when connecting

### ISSUE THREAD

**Issue by Lurx0720** [jxaq/From-the-Fog-#1]
My friends and I are having some problems with trying to install this modpack on a server. We have checked every mod if it is client- or server-side and removed the client side mods. We are running into the problem when someone is loading in and spawned, that the server closes directly and no error message shows in the logs. It would be nice if there was a pre-made server pack. Thanks for any help in advance.

**Comment by Jackson5546** [comment]
Personally, I have had a server on this modpack running, I can post the server zip file. Anyways, what are you running the server on (such as Pterodactyl, Puffer Panel etc.)?

**Comment by Lurx0720** [comment]
it would be nice if you sent the zip pls. and i just use normal forge for the server, and the host im using is mc host 24. thanks for your help
